const CREDENTIALS_LOGIN_PROVIDER = 'credentials_login_provider';
const GOOGLE_LOGIN_PROVIDER = 'google_login_provider';
const LINKEDIN_LOGIN_PROVIDER = 'linkedin_login_provider';
const FACEBOOK_LOGIN_PROVIDER = 'facebook_login_provider';

const LOGIN_PROVIDERS = [GOOGLE_LOGIN_PROVIDER];

export { LOGIN_PROVIDERS, CREDENTIALS_LOGIN_PROVIDER, GOOGLE_LOGIN_PROVIDER, LINKEDIN_LOGIN_PROVIDER, FACEBOOK_LOGIN_PROVIDER};
