# Generated by Django 2.1.3 on 2018-11-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_end_6th_year', models.IntegerField()),
                ('student_end_9th_year', models.IntegerField()),
                ('study_track_9th', models.IntegerField(choices=[(0, 'vmbo bl/kl'), (1, 'vmbo gl/tl'), (2, 'havo'), (3, 'vwo')])),
                ('exit_school_6th_grade', models.IntegerField()),
                ('exit_school_6th_recommendation', models.CharField(max_length=30)),
                ('correct_math_cito', models.IntegerField()),
                ('correct_study_skills_cito', models.IntegerField()),
                ('correct_language_cito', models.IntegerField()),
                ('gender', models.BooleanField(choices=[(0, 'male'), (1, 'female')])),
                ('highest_educated_parent_level', models.CharField(max_length=100)),
                ('origin', models.IntegerField(choices=[(0, 'Limburg'), (1, 'Non-Dutch'), (2, '(Other) Dutch')])),
                ('home_language', models.IntegerField(choices=[(0, 'Nederlands'), (1, 'andere taal'), (2, 'dialect')])),
                ('student_birth_year', models.IntegerField()),
                ('student_birth_month', models.IntegerField()),
                ('primary_school', models.IntegerField()),
                ('secondary_school', models.IntegerField()),
                ('secondary_school_location', models.IntegerField()),
                ('region', models.IntegerField(choices=[(0, 'North of South Limburg (Sittard area)'), (1, 'South-East Limburg (Heerlen area)'), (2, 'South-West Limburg (Maastricht area)'), (3, 'Central Limburg'), (4, 'North Limburg')])),
                ('iq_6th', models.IntegerField()),
                ('iq_9th', models.FloatField()),
                ('dutch_language_test_9th', models.FloatField()),
                ('math_test_9th', models.FloatField()),
                ('school_motivation_score', models.FloatField()),
                ('social_capital_score', models.FloatField()),
                ('parent_support_home_lessons', models.IntegerField(choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')])),
                ('parent_support_homework_help', models.IntegerField(choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')])),
                ('parent_support_motivation', models.IntegerField(choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')])),
                ('parent_support_professional', models.IntegerField(choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')])),
                ('ever_registered_as_school_drop_out', models.BooleanField(choices=[(0, 'no'), (1, 'yes')])),
                ('family_both_parents', models.BooleanField(choices=[(0, 'no'), (1, 'yes')])),
            ],
        ),
    ]
