# Generated by Django 2.1.3 on 2018-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='correct_language_cito',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='correct_math_cito',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='correct_study_skills_cito',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='dutch_language_test_9th',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='ever_registered_as_school_drop_out',
            field=models.BooleanField(blank=True, choices=[(0, 'no'), (1, 'yes')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='exit_school_6th_grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='exit_school_6th_recommendation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='family_both_parents',
            field=models.BooleanField(blank=True, choices=[(0, 'no'), (1, 'yes')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(0, 'male'), (1, 'female')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='highest_educated_parent_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='home_language',
            field=models.IntegerField(blank=True, choices=[(0, 'Nederlands'), (1, 'andere taal'), (2, 'dialect')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='iq_6th',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='iq_9th',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='math_test_9th',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='origin',
            field=models.IntegerField(blank=True, choices=[(0, 'Limburg'), (1, 'Non-Dutch'), (2, '(Other) Dutch')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='parent_support_home_lessons',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='parent_support_homework_help',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='parent_support_motivation',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='parent_support_professional',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'some'), (2, 'a lot'), (3, 'quite a lot')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='primary_school',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'North of South Limburg (Sittard area)'), (1, 'South-East Limburg (Heerlen area)'), (2, 'South-West Limburg (Maastricht area)'), (3, 'Central Limburg'), (4, 'North Limburg')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='school_motivation_score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='secondary_school',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='secondary_school_location',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='social_capital_score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='student_birth_month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='student_birth_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='student_end_6th_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='student_end_9th_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='study_track_9th',
            field=models.IntegerField(blank=True, choices=[(0, 'vmbo bl/kl'), (1, 'vmbo gl/tl'), (2, 'havo'), (3, 'vwo')]),
        ),
    ]
