# Generated by Django 2.1.3 on 2018-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20181130_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='iq_9th',
            field=models.FloatField(null=True),
        ),
    ]
