# Generated by Django 2.1.3 on 2018-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20181201_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('video', models.URLField()),
                ('image', models.URLField()),
                ('summary', models.TextField()),
                ('question', models.CharField(max_length=200)),
                ('answer0', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(max_length=200)),
                ('correct_answer', models.IntegerField()),
            ],
        ),
    ]
