# Generated by Django 2.1.3 on 2018-12-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_concept'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(-1, 'lower'), (0, 'same'), (1, 'higher')])),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='related',
            field=models.ManyToManyField(through='analytics.ConceptRelation', to='analytics.Concept'),
        ),
    ]
