# Generated by Django 2.1.3 on 2018-12-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20181201_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptrelation',
            name='from_concept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_concept', to='analytics.Concept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conceptrelation',
            name='to_concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_concept', to='analytics.Concept'),
            preserve_default=False,
        ),
    ]
