# Generated by Django 2.1.3 on 2018-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20181201_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='video',
            field=models.CharField(max_length=20),
        ),
    ]
