# Generated by Django 2.1.3 on 2018-12-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_concept_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimarySchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straatnaam_correspondentie_adres', models.CharField(max_length=80)),
                ('nodaal_gebied_naam', models.CharField(max_length=80)),
                ('gemeentenaam', models.CharField(max_length=80)),
                ('rmc_regio_naam', models.CharField(max_length=80)),
                ('rpa_gebied_naam', models.CharField(max_length=80)),
                ('wgr_gebied_code', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=80)),
                ('postcode_correspondentie_adres', models.CharField(max_length=80)),
                ('gemeente_nummer', models.CharField(max_length=80)),
                ('onderwijsgebied_naam', models.CharField(max_length=80)),
                ('plaatsnaam', models.CharField(max_length=80)),
                ('plaatsnaam_correspondentieadres', models.CharField(max_length=80)),
                ('denominatie', models.CharField(max_length=80)),
                ('coropgebied_naam', models.CharField(max_length=80)),
                ('brin_nummer', models.CharField(max_length=80)),
                ('nodaal_gebied_code', models.CharField(max_length=80)),
                ('bevoegd_gezag_nummer', models.CharField(max_length=80)),
                ('internetadres', models.CharField(max_length=80)),
                ('provincie', models.CharField(max_length=80)),
                ('wgr_gebied_naam', models.CharField(max_length=80)),
                ('rmc_regio_code', models.CharField(max_length=80)),
                ('huisnummer_toevoeging', models.CharField(max_length=80)),
                ('rpa_gebied_code', models.CharField(max_length=80)),
                ('instellings_naam', models.CharField(max_length=80)),
                ('huisnummer_toevoeging_correspondentieadres', models.CharField(max_length=80)),
                ('onderwijsgebied_code', models.CharField(max_length=80)),
                ('coropgebied_code', models.CharField(max_length=80)),
                ('straatnaam', models.CharField(max_length=80)),
                ('telefoonnummer', models.CharField(max_length=80)),
            ],
        ),
    ]
